redis:
  enabled: false
  host: "localhost"
  port: 6379
  auth:
    enabled: false
    password: ""
  channel-id: 1

vault-integration: false
papi-integration: false

mongo:
  enabled: false
  host: "localhost"
  port: 27017
  database: "lCore"
  auth:
    enabled: false
    username: ""
    password: ""
    auth-db: ""

chat-format: "%player-prefix%%player-name%&7: %message%"
server-name: "lCore"
timezone: "EST"

report-cooldown: "1m"
report-on-cooldown: "&cYou are currently on cooldown for reporting. Try again in %time%"
use-protected-ip-storage: true
failed-to-load-profile: "&cFailed to load your profile. Contact an admin."

grant:
  active-display: "&a&lACTIVE"
  inactive-display: "&c&lINACTIVE"
  granted:
    expired: "&aYour %rank% has just expired&a."
    sender: "&aYou have just granted %player% &athe %rank%&a for &e%time%&a."
    target: "&aYou have just been granted &athe %rank%&a for &e%time%&a."

punish:
  alts:
    header:
      - ''
      - '&6&lAlts'
      - ''
    offline: "&7"
    online: "&a"
    muted: "&e"
    banned: "&c"
    blacklisted: "&4"
    info-line: "&7Offline &f- &aOnline &f- &eMuted &f- &cBanned &f- &4Blacklisted"
  blacklist:
    display: "&0&lBlacklist"
    kick-message: "&cYour account is blacklisted from the Example Network\n&cThis punishment cannot be appealed\n"
  mute:
    display: "&6&lMute"
    resolved-message: "&aYour mute has been lifted. You may now chat."
    message: "&cYou have been muted for %reason%\n&cExpires: 7 days"
  ban:
    display: "&c&lBan"
    kick-message: "&cYour account is banned from the Example Network.\n%temp-format%\n\n&cIf you feel this punishment is unjust, you may appeal at:\nhttp://www.lbuddyboy.me"
    temporary-format: "&cExpires: %time%"
  kick:
    display: "&e&lKick"
    kick-message: "&cYou have been kicked from the server.\n&cReason: %reason%"
  warn:
    display: "&a&lWarn"
    message: "&cYou have been warned for %reason%\n&cExpires: 7 days"
    warns-before-command: 3
    warn-command: "ban %player% 3d Reached maximum amount of warns"
    warn-last-time: "7d"

reports:
  sent-sender: "&aWe have received your request for help and we will assist you shortly."
  go-to-server-message: "&7(( Click here to go to their server ))" # leave blank to not send the message
  tp-sender-message: "&7(( Click here to go to teleport to the sender ))" # leave blank to not send the message
  tp-target-message: "&7(( Click here to go to teleport to the target ))" # leave blank to not send the message
  report-staff-message:
    - '&6&lREPORT &f- &e%sender%&f needs assistance on &e%server%&f.'
    - '&6Target&f: %target%'
    - '&6Reason&f: %reason%'
  helpop-staff-message:
    - '&6&lHELPOP &f- &e%sender%&f needs assistance on &e%server%&f.'
    - '&6Reason&f: %reason%'
  staff-resolved-message: "&aSuccessfully resolved that report. It has now been moved in to the resolved reports section."
  staff-deleted-message: "&aSuccessfully deleted that report. It can no longer be recovered."
rank:
  edit:
    menu-title: "&6Editing: &r%rank%"
  non-existant: "&cThat rank does not exist"
  exists: "&cThat rank already exists"
  deleted: "&aSuccessfully deleted the %rank%&a."
  created: "&aSuccessfully created the %rank%&a."
  rename: "&aSucessfully renamed the %rank% to %new%"
  setPrefix: "&aSucessfully set the prefix of %rank% to %new%"
  setDisplay: "&aSucessfully set the displayname of %rank% to %new%"
  setWeight: "&aSucessfully set the weight of %rank% to %new%"
  setColor: "&aSucessfully set the color of %rank% to %new%"
  addPerm: "&aSucessfully added the %perm% permission to %rank%"
  removePerm: "&aSucessfully removed the %perm% permission from %rank%"
  hasPerm: "&cThat rank already has that permission."
  noPerm: "&cThat rank does not have that permission."
  list:
    header:
      - " "
      - "&6&lRank Info"
      - " "
    format: "&7%right_arrow%&r %rank% &7(Weight: %weight%)"

essentials:
  heal:
    message: "&aYou are now full health."
  feed:
    message: "&aYou are now full hunger."
  gamemode:
    message: "&fSwitched to &6%mode%&f mode."